yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('create/', views.post_create, name='post_create'),
]

yatube/users/urls.py
from django.contrib.auth.views import LogoutView, LoginView, PasswordResetView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout',
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login',
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(),
        name='password_reset',
    )
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField(
        help_text='Текст нового поста',
        verbose_name='Текст поста',
    )
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        help_text='Группа, к которой будет относиться пост',
        verbose_name='Группа',
    )

    def __str__(self) -> str:
        return self.text[:15]

    class Meta:
        ordering = ['-pub_date']

yatube/posts/forms.py
from .models import Post
from django import forms


class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ('text', 'group')

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = {'first_name', 'last_name', 'username', 'email'}

yatube/about/views.py
from django.views.generic.base import TemplateView


# Описать класс AboutAuthorView для страницы about/author
class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Group, User
from .forms import PostForm
from django.contrib.auth.decorators import login_required


def index(request):
    template = 'posts/index.html'
    post_list = Post.objects.all()
    context = {
        'page_obj': pagination(request, post_list),
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    context = {
        'group': group,
        'page_obj': pagination(request, post_list),
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    profile = User.objects.get(username=username)
    post_list = profile.posts.all()
    context = {
        'profile': profile,
        'page_obj': pagination(request, post_list),
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = Post.objects.get(pk=post_id)
    context = {
        'post': post,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    if request.method == 'POST':
        form = PostForm(request.POST)

        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', post.author)
    form = PostForm()
    return render(request, template, {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    is_edit = True
    template = 'posts/create_post.html'
    form = PostForm(request.POST or None, instance=post)
    if request.user != post.author:
        return redirect("posts:post_detail", post_id)
    if request.method == 'POST' and form.is_valid():
        post.text = form.cleaned_data['text']
        post.group = form.cleaned_data['group']
        post.save()
        return redirect('posts:post_detail', post.id)
    context = {
        'form': form,
        'is_edit': is_edit,
        'post': post,
    }
    return render(request, template, context)


def pagination(request, list):
    paginator = Paginator(list, 10)
    page_number = request.GET.get('page')
    return paginator.get_page(page_number)

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %} 
{% block title %}
  Об авторе проекта
{% endblock %}
{%block content %}
<div class="container py-5">
  <h1>Привет, я автор</h1>
  <p>
    Я учусь на 3 курсе направления "Фундаментальная информатика и информационные
    технологии" на <b>МЕХМАТ</b> ЮФУ
  </p>
  <p>
    В данный момент увлекаюсь созданием видеоигр на Unity, а также пробую себя в
    вебе.
  </p>
</div>
{% endblock %}

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row">
    <h1>Вот что я умею</h1>

    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Python</li>
        <li class="list-group-item">Django</li>
        <li class="list-group-item">C#</li>
        <li class="list-group-item">Unity</li>
        <li class="list-group-item">C++</li>
        <li class="list-group-item">C</li>
        <li class="list-group-item">Assembler Intel 8088</li>
        <li class="list-group-item">Java</li>
        <li class="list-group-item">Pascal.ABC</li>
        <li class="list-group-item">Prolog</li>
      </ul>
    </aside>  
    <article class="col-12 col-md-9">
      <p></p>
    </article>
  </div>
</div>
{% endblock %} 

yatube/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="../img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="../img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
{% include 'includes/header.html' %}
<main>
{% block content %}
{% endblock %}
</main>
{% include 'includes/footer.html' %}
</body>
</html>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
</footer> 

yatube/templates/includes/header.html
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        {% load static %}
        <img
          src="{% static 'img/logo.png' %}"
          width="30"
          height="30"
          class="d-inline-block align-top"
          alt=""
        />
        <span style="color: red">Ya</span>tube
      </a>
      {% with request.resolver_match.view_name as view_name %}
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a
            class="nav-link {% if view_name == 'about:author' %}active{% endif %}"
            href="{% url 'about:author' %}"
            >Об авторе</a
          >
        </li>
        <li class="nav-item">
          <a
            class="nav-link {% if view_name == 'about:tech' %}active{% endif %}"
            href="{% url 'about:tech' %}"
            >Технологии</a
          >
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a
            class="nav-link {% if view_name == 'posts:post_create' %}active{% endif %}"
            href="{% url 'posts:post_create' %}"
            >Новая запись</a
          >
        </li>

        <li class="nav-item">
          <a class="nav-link link-light" href="{% url 'users:password_reset' %}"
            >Изменить пароль</a
          >
        </li>

        <li class="nav-item">
          <a
            class="nav-link link-light {% if view_name == 'users:logout' %}active{% endif %}"
            href="{% url 'users:logout' %}"
            >Выйти</a
          >
        </li>
        <li>Пользователь: {{ user.username }}</li>
        {% else %}
        <li class="nav-item">
          <a
            class="nav-link link-light {% if view_name == 'users:login' %}active{% endif %}"
            href="{% url 'users:login' %}"
            >Войти</a
          >
        </li>
        <li class="nav-item">
          <a
            class="nav-link link-light {% if view_name == 'users:signup' %}active{% endif %}"
            href="{% url 'users:signup' %}"
            >Регистрация</a
          >
        </li>
        {% endif %}
      </ul>
      {% endwith %}
    </div>
  </nav>
</header>

yatube/templates/includes/post.html
<article>
  <ul>
    {% if not profile %}
    <li>
      Автор: {{ post.author.get_full_name }}
      <a href="{% url 'posts:profile' post.author %}">
        все посты пользователя
      </a>
    </li>
    {% endif %}
    <li>Дата публикации: {{ post.pub_date|date:'j E Y' }}</li>
  </ul>
  <p>{{ post.text }}</p>
  <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
</article>
{% if post.group %}
<a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
{% endif %}

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
{% if is_edit %}
    Редактировать запись
{% else %}
    Добавить запись
{% endif %}   
{% endblock %}
{% block content %}
{% load user_filters %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">       
            {% if is_edit %}
                Редактировать запись
            {% else %}
                Добавить запись
            {% endif %}               
        </div>
        <div class="card-body">
            {% load user_filters %} 
            {% if form.errors %}
                {% for field in form %}
                {% for error in field.errors %}            
                    <div class="alert alert-danger">
                    {{ error|escape }}
                    </div>
                {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    {{ error|escape }}
                </div>
                {% endfor %}
            {% endif %}

            <form method="post"
                  action="{% if is_edit %}
                            {% url 'posts:post_edit' post.id %}
                          {% else %}
                            {% url 'posts:post_create' %} 
                          {% endif %}">
            {% csrf_token %}
            {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}

            <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                    {% if is_edit %}
                      Сохранить
                    {% else %}
                      Добавить
                    {% endif %}               
                  </button> 
            </div>
            </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
    Записи сообщества {{ group.title }}
{% endblock %}
{% block content %}
    <div class="container">
        <h1>{{ group.title }}</h1>
        <p>{{ group.description }}</p>

        {% for post in page_obj %}
            {% include 'includes/post.html' %}
            {% if not forloop.last %}
                <hr>
            {% endif %}
        {% endfor %}

        {% include 'posts/includes/paginator.html' %}
    </div>
{% endblock %}

yatube/templates/posts/includes/paginator.html
{% comment %}
Отрисовываем навигацию паджинатора только если
все посты не помещаются на первую страницу
{% endcomment %}
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  Последние обновления на сайте
{% endblock %}
{% block content %}
<div class="container">        
  <h1>Последние обновления на сайте</h1>

  {% for post in page_obj %}
    {% include 'includes/post.html' %}
    {% if not forloop.last %} 
      <hr>
    {% endif %}
  {% endfor %}
  
  {% include 'posts/includes/paginator.html' %}
</div>  
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
  Пост {{ post.text|truncatewords:30 }}
{% endblock %}
{% block content %}
<div class="container py-5">    
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:'j E Y' }}
        </li>

        {% if post.group %}
        <li class="list-group-item">
          Группа: {{ post.group.title }}
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        </li>
        {% endif %}

        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>

        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: {{ post.author.posts.count }}
        </li>

        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>{{ post.text }}</p>
      <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
        редактировать запись
      </a>
    </article>
   
  </div>
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}
  Профайл пользователя {{ profile.get_full_name }}
{% endblock %} 
{% block content %} 
<div class="container py-5">    
  <h1>Все посты пользователя {{ profile.get_full_name }}</h1>
  <h3>Всего постов: {{ profile.posts.count }}</h3>   

  {% for post in page_obj %}
    {% include 'includes/post.html' %}
    {% if not forloop.last %} 
      <hr>
    {% endif %}
  {% endfor %}

  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %} 
{% block title %}
  Вы вышли из системы
{% endblock %} 
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Выход</div>
      <div class="card-body">
        <p>Вы вышли из своей учётной записи. Ждём вас снова!</p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}
  Войти
{% endblock %} 
{% block content%} 
{% load user_filters %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Войти на сайт</div>
      <div class="card-body">
        {% if form.errors %} 
          {% for field in form %} 
            {% for error in field.errors %}
              <div class="alert alert-danger">{{ error|escape }}</div>
            {% endfor %}
          {% endfor %} 
          {% for error in form.non_field_errors %}
            <div class="alert alert-danger">{{ error|escape }}</div>
          {% endfor %} 
        {% endif %}

        <form
          method="post"
          {% if action_url %}
            action="{% url action_url %}"
          {% endif %}
        >
          {% csrf_token %}
          {% for field in form %}
          <div
            class="form-group row my-3"
            {% if field.field.required %}
              aria-required="true"
            {% else %}
              aria-required="false"
            {% endif %}
          >
            <label for="{{ field.id_for_label }}">
              {{ field.label }} {% if field.field.required %}
              <span class="required text-danger">*</span>
              {% endif %}
            </label>
            <div>
              {{ field|addclass:'form-control' }} {% if field.help_text %}
              <small
                id="{{ field.id_for_label }}-help"
                class="form-text text-muted"
              >
                {{ field.help_text|safe }}
              </small>
              {% endif %}
            </div>
          </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">Войти</button>
            <a href="{% url 'users:password_reset' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %} 
{% block title %}
  Зарегистрироваться
{% endblock %} 
{% block content %}
{% load user_filters %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Зарегистрироваться</div>
      <div class="card-body">
        {% if form.errors %} 
          {% for field in form %} 
            {% for error in field.errors %}
              <div class="alert alert-danger">{{ error|escape }}</div>
            {% endfor %}
          {% endfor %} 
          {% for error in form.non_field_errors %}
            <div class="alert alert-danger">{{ error|escape }}</div>
          {% endfor %} 
        {% endif %}

        <form method="post" action="{% url 'users:signup' %}">
          {% csrf_token %} 
          {% for field in form %}
          <div class="form-group row my-3">
            <label for="{{ field.id_for_label }}">
              {{ field.label }} {% if field.field.required %}
              <span class="required text-danger">*</span>
              {% endif %}
            </label>
            {{ field|addclass:'form-control' }} 
            {% if field.help_text %}
              <small
                id="{{ field.id_for_label }}-help"
                class="form-text text-muted"
              >
              {{ field.help_text|safe }}
              </small>
            {% endif %}
          </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Зарегистрироваться
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}